---

- name: Install kiosk packages
  ansible.builtin.apt:
    name:
      - chromium
      - cifs-utils
      - feh
      - imagemagick
      - libheif1
      - openbox
      - unclutter
      - x11-utils
      - xauth
      - xinit
      - xprintidle
      - xserver-xorg-core
    state: present
    update_cache: true

- name: Create kiosk user
  ansible.builtin.user:
    name: "{{ kiosk_user }}"
    shell: /bin/bash
    create_home: true

- name: Ensure required directories exists
  ansible.builtin.file:
    path: "/home/{{ kiosk_user }}/{{ directories }}"
    state: directory
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: "0755"
  loop:
    - ".config/openbox"
    - "{{ kiosk_slideshow_image_dir }}" 
  loop_control:
    loop_var: directories

- name: Deploy configuration files
  ansible.builtin.copy:
    src: "{{ config_file.src }}"
    dest: "{{ config_file.dest }}"
    owner: "{{ config_file.owner|default(kiosk_user) }}"
    group: "{{ config_file.group|default(kiosk_user) }}"
    mode: "{{ config_file.mode|default('0644') }}"
  loop:
    - {"src": "rc.xml", "dest": "/home/{{ kiosk_user }}/.config/openbox/rc.xml"}
    - {"src": "bash_login", "dest": "/home/{{ kiosk_user }}/.bash_login"}
  loop_control:
    loop_var: config_file
  notify: Restart getty service

- name: Deploy configuration templates
  ansible.builtin.template:
    src: "{{ config_template.src }}"}
    dest: "{{ config_template.dest }}"
    owner: "{{ config_template.owner|default(kiosk_user) }}"
    group: "{{ config_template.group|default(kiosk_user) }}"
    mode: "{{ config_template.mode|default('0755') }}"
  loop:
    - {"src": "getty_service.j2", "dest": "/etc/systemd/system/getty@tty1.service", owner: "root", group: "root"}
    - {"src": "xinitrc.j2", "dest": "/home/{{ kiosk_user }}/.xinitrc"}
    - {"src": "feh-screensaver.sh.j2", "dest": "/home/{{ kiosk_user }}/feh-screensaver.sh", mode: "0755"}
    - {"src": "90-monitor.conf.j2", "dest": "/usr/share/X11/xorg.conf.d/90-monitor.conf", owner: "root", group: "root"}
  loop_control:
    loop_var: config_templates
  notify: Restart getty service

- name: enable dsi for waveshare 10 inch display
  when: kiosk_display_type == "dsi-waveshare"
  ansible.builtin.blockinfile:
    path: /boot/firmware/config.txt
    create: true
    insertafter: "dtoverlay=v4c-kms-v3d"
    block: |
      dtoverlay=vc4-kms-dsi-waveshare-panel-v2,10_1_inch_a
      display_default_lcd=1
      max_framebuffers=2
      framebuffer_width=800
      framebuffer_height=1280
  notify: Restart getty service

- name: Samba sync setup
  when: kiosk_samba_enabled
  block:
    - name: Create samba mount point
      ansible.builtin.file:
        path: "{{ kiosk_samba_mount_point }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy samba sync script
      ansible.builtin.template:
        src: kiosk_samba_sync.sh.j2
        dest: /usr/local/bin/kiosk_samba_sync.sh
        owner: root
        group: root
        mode: "0755"

    - name: Schedule samba sync cron job
      ansible.builtin.template:
        src: kiosk-samba-sync.cron.j2
        dest: /etc/cron.d/kiosk-samba-sync
        owner: root
        group: root
        mode: "0640"
  tags: [samba]

- name: Remove samba sync cron job
  ansible.builtin.file:
    path: /etc/cron.d/kiosk-samba-sync
    state: absent
  when: not kiosk_samba_enabled
  tags: [samba]